"""Create funds table with commitment stored as text.

Revision ID: 0001
Revises:
"""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE funds (
            id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fund_name    text    NOT NULL,
            strategy     text    NOT NULL,
            vintage_year integer NOT NULL,
            commitment   text    NOT NULL
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE funds")
